import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  weight:["400","500","600","700","800"],
  subsets: ["latin"],
});



export const metadata = {
  title: "Meiniger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
